// Exercise - 3 (Tell Me a Joke)

// Create a website with a div tag conatining a random joke given an array of jokes. Use math.random and fetch jokes from the internet . Your website should show a random joke everytime on reload. Min length of jokes array should be 10.

function gen_joke(){

const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How does a penguin build its house? Igloos it together.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "How do you organize a space party? You planet.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "Why did the coffee file a police report? It got mugged.",
    "How does a penguin build its house? Igloos it together.",
    "What do you call a pile of cats? A meowtain.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "How does a penguin build its house? Igloos it together.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How does a penguin build its house? Igloos it together.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "How do you organize a space party? You planet.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call a pile of cats? A meowtain.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an alligator in a vest? An investigator.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why was the math book sad? It had too many problems.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "How do you organize a space party? You planet.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "Why did the stadium get hot after the game? All the fans left.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why was the math book sad? It had too many problems.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why did the cookie go to the doctor? Because it felt crumby.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "How do you organize a space party? You planet.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "Why don't you write with a broken pencil? Because it's pointless.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the coffee file a police report? It got mugged."
];

const r = Math.floor(Math.random() * 199);


if(r <= jokes.length-1){
    document.getElementsByClassName("rand_joke")[0].innerHTML = jokes[r];
}


}